# Basic
title: 袁凤鸣
subtitle: 欢迎来到我的个人站~
description: 最好的学习时间是十年前，其次是现在！
# 头像里面的标题
avatarTitle: Mingo
# 头像里面的描述
avatarDesc: iOS / 个人笔记
url: "http://baixin.io"

# Comment
comment:
    # disqus: leopard
    duoshuo: yfmingo#leopard 

# Social
social:
    weibo: 3414294504 
    github: yfming93
    # twitter: 
    mail: yfmingo@163.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 9241bf337f3366ee1aea666f56466cf1
       #8ba1c6be0953b6f9c2ba38e57f615421   原来模板

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-89635745-1
       #UA-84134159-3 原来模板

    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 关于我, description: about, url: '/about'}

# Pagination
gems: [jekyll-paginate] #[jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


