# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 袁凤鸣的博客 | Fleeming's Blog
SEOTitle: 袁凤鸣的博客 | Fleeming's Blog
description: "前端开发与设计 | 袁凤鸣，Web & Mobile Lover，Front-End Engineer | 这里是 @Fleeming袁凤鸣 的个人博客，与你一起发现更大的世界。"
keyword: "袁凤鸣, Fleeming袁凤鸣, Fleeming, @Fleeming, 袁凤鸣的博客, Fleeming's Blog, 博客, 个人网站, 互联网, 前端, 设计, 产品"
brief-intro: Front-end Dev Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.yfmingo.cn" # the base hostname & protocol for your site


permalink: /:year/:month/:day/:title/

# other links
twitter_username: #gaohaoyang126
facebook_username: #gaohaoyang.water
github_username:  yfming93
email: yfmingo@163.com
weibo_username: yfming
zhihu_username: yfmingo
wangyiyun_username: "278546999"
linkedIn_username: #gaohaoyang
dribbble_username:
rss: feed.xml
description_footer: 生命不息，折腾不止！细节决定成败，心态造就未来！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: fleeming

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 1b99a6addc30aac294cc600d2664427c
google_analytics_id: UA-89635745-1 # google 分析追踪id

# Build settings
markdown: kramdown
highlighter:    rouge
kramdown:
  input:                     GFM
  enable_coderay:            true
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            true
  hard_wrap:                 true
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"

 

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
paginate: 6

algolia:
   application_id: 'KRITZR1P9L'
   index_name:     'KRITZR1P9L'
   search_only_api_key: '5fdcf330fc6ad3f56dff2fdf3a3f874d'
