# Basic
title: Mingoy
subtitle: Front-end Dev Engineer
description: 欢迎来到我的个人网站~
# 头像里面的标题
avatarTitle: 袁凤鸣
# 头像里面的描述
avatarDesc: iOS/H5/设计师
url: "http://yfmingo.cn"

# Comment
comment:
    provider: duoshuo
    duoshuo:
     short_name: yfmingo

# Social
social:
    weibo: 123456789
    weixing: 13720187713 
    github: yfming93
    # twitter: 
    mail: yfmingo@163.com
    csdn: yfming93

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 1b99a6addc30aac294cc600d2664427c 

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga: yfmingo.cn
id: UA-89635745-1   
#  host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/MengZheK/kangblog.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}   
    - {title: 留言, description: liuyan, url: '/liuyan'}
    - {title: 资源, description: ziyuan, url: '/ziyuan'}
    - {title: 关于我, description: about, url: '/about'}

          
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


